//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Eugen (WebDucer) Richter")]
[assembly: AssemblyCopyright("MIT - (c) 2018 Eugen [WebDucer] Richter")]

// Metadata Attributes
[assembly: AssemblyMetadata("git_hash", "bacb0a5d473a8e844a15db29980550c166721120")]
[assembly: AssemblyMetadata("sem_ver", "0.3.0-unstable.2")]
[assembly: AssemblyMetadata("build_date", "2018-06-30")]
